-- DDL Script to create all necessary tables for NEMS

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE STUDENT_SEQ';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ALLOTMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GRIEVANCE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RESULT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REGISTRATION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STUDENT_PHONE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STUDENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BRANCH CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COLLEGE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXAM_SESSION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXAM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CENTER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE STUDENT_SEQ START WITH 1001 INCREMENT BY 1;

CREATE TABLE CENTER (
    CENTER_ID NUMBER PRIMARY KEY,
    CENTER_NAME VARCHAR2(100),
    CENTER_CITY VARCHAR2(100)
);

CREATE TABLE EXAM (
    EXAM_CODE VARCHAR2(20) PRIMARY KEY,
    EXAM_NAME VARCHAR2(100),
    TOTAL_MARKS NUMBER
);

CREATE TABLE EXAM_SESSION (
    SESSION_ID NUMBER PRIMARY KEY,
    EXAM_CODE VARCHAR2(20) REFERENCES EXAM(EXAM_CODE),
    PHASE VARCHAR2(50),
    SHIFT VARCHAR2(50),
    EXAM_DATE DATE
);

CREATE TABLE COLLEGE (
    COLLEGE_ID NUMBER PRIMARY KEY,
    COLLEGE_NAME VARCHAR2(100),
    COLLEGE_CITY VARCHAR2(100)
);

CREATE TABLE BRANCH (
    BRANCH_CODE VARCHAR2(20) PRIMARY KEY,
    BRANCH_NAME VARCHAR2(100)
);

CREATE TABLE STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100) UNIQUE,
    DOB DATE,
    STREET VARCHAR2(100),
    CITY VARCHAR2(50),
    STATE VARCHAR2(50),
    CATEGORY VARCHAR2(20),
    CENTER_ID NUMBER REFERENCES CENTER(CENTER_ID)
);

CREATE TABLE STUDENT_PHONE (
    STUDENT_ID NUMBER REFERENCES STUDENT(STUDENT_ID),
    PHONE_NUMBER VARCHAR2(15),
    PRIMARY KEY (STUDENT_ID, PHONE_NUMBER)
);

CREATE TABLE REGISTRATION (
    STUDENT_ID NUMBER REFERENCES STUDENT(STUDENT_ID),
    SESSION_ID NUMBER REFERENCES EXAM_SESSION(SESSION_ID),
    REGISTRATION_DATE DATE,
    PRIMARY KEY (STUDENT_ID, SESSION_ID)
);

CREATE TABLE RESULT (
    STUDENT_ID NUMBER REFERENCES STUDENT(STUDENT_ID),
    SESSION_ID NUMBER REFERENCES EXAM_SESSION(SESSION_ID),
    SCORE NUMBER,
    PERCENTILE NUMBER(5,2),
    PRIMARY KEY (STUDENT_ID, SESSION_ID)
);

CREATE TABLE GRIEVANCE (
    STUDENT_ID NUMBER REFERENCES STUDENT(STUDENT_ID),
    TICKET_NO NUMBER PRIMARY KEY,
    ISSUE_TYPE VARCHAR2(50),
    DESCRIPTION VARCHAR2(500),
    STATUS VARCHAR2(20)
);

CREATE TABLE ALLOTMENT (
    STUDENT_ID NUMBER REFERENCES STUDENT(STUDENT_ID),
    ROUND_NO NUMBER,
    COLLEGE_ID NUMBER REFERENCES COLLEGE(COLLEGE_ID),
    BRANCH_CODE VARCHAR2(20) REFERENCES BRANCH(BRANCH_CODE),
    ALLOCATED_CATEGORY VARCHAR2(20),
    STATUS VARCHAR2(20),
    PRIMARY KEY (STUDENT_ID, ROUND_NO)
);

COMMIT;
